### ISSUE TITLE
Kmod version out of dangwrt support

### ISSUE THREAD

**Issue by strayedstar** [pi0/bpi-r4-openwrt#3]
The current kernel version is 6.1.75,dangwrt fix many bugs on bpi r4.
So,can we upgrade komd to 6.1.75 version?

**Comment by pi0** [comment]
Hi. Just compiled and synced from latest commit you can find here: https://dl.pi0.io/openwrt/bpi-r4/targets/mediatek/filogic/

(packages use `6.1.77`)
