### ISSUE TITLE
gcci-multilib has no installation candidate, redundant on ARM hosts 

### ISSUE THREAD

**Issue by mmisiewicz** [pi0/bpi-r4-openwrt#4]
I'm on macOS on an M1 ultra. 

When building the docker container using ` ./build.sh scripts/build -j 10`, the following issue appears:

```
5.735
5.735 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
5.735
5.753 Reading package lists...
6.254 Building dependency tree...
6.389 Reading state information...
6.394 Package gcc-multilib is not available, but is referred to by another package.
6.394 This may mean that the package is missing, has been obsoleted, or
6.394 is only available from another source
6.394
6.395 E: Package 'gcc-multilib' has no installation candidate
------
Dockerfile:5
--------------------
   4 |
   5 | >>> RUN apt update && apt dist-upgrade -fy && apt install -fy build-essential ccache ecj fastjar file g++ gawk \
   6 | >>> gettext git java-propose-classpath libelf-dev libncurses5-dev \
   7 | >>> libncursesw5-dev libssl-dev python2.7-dev python3 unzip wget \
   8 | >>> python3-distutils python3-setuptools python3-dev rsync subversion \
   9 | >>> swig time xsltproc zlib1g-dev htop vim gcc-multilib libpam-dev liblzma-dev libsnmp-dev
  10 |
--------------------
```

Since multi arch isn't needed on an ARM host, removing `gcc-multilib` from the apt install command works around this issue.

**Comment by pi0** [comment]
Hi! If you can confirm without this dependency base build goes well (I guess I picked it from official docs list somewhere) PR welcome to remove it 👍🏼

**Comment by strayedstar** [comment]
In fact,you can make it without gcc-multilib,I build all of c/cpp (include this openwrt images) on my archlinux lxc container,I'm using gcc/++-12 and it always work.

**Comment by mmisiewicz** [comment]
On MacOS removing gcc-multilib allows the container build to succeed. I also reproduced the same issue on Ubuntu on arm64. For both platforms adding a little bit of shell logic to test `arch` would mitigate.

However, the build still fails on both platforms. On macOS openwrt will not build because the mounted directory inside the container fails because the filesystem is case insensitive. On Ubuntu arm64, the openwrt build fails for some other reason that's not clear... looks like a broken build upstream.

**Comment by pi0** [comment]
Ah, that's sad to hear. I thought APFS is case sensitive now adays :( BTW I can happily continue pushing the latest builds as I have a dedicated intel server around if you want me to do any config changes on builds just ask 👍🏼

**Comment by mmisiewicz** [comment]
I’m trying to get a build that includes kmod-ath11k and kmod-ath11k-pci. I didn’t see them in the repositories!

**Comment by mmisiewicz** [comment]
No longer needed since bpi-r4 support just got merged to main upstream :)
